---
- name: ans
  hosts: ansible 
  become: yes
  become_user: root
  roles:
    - dir
    - ansible
    - chk_pg
    - cpy
  

- name: postgres
  hosts: postgres
  become: yes
  become_user: root
  roles:
    - postgres

